---
galaxy_info:
  author: ""
  description: Deploy Alloy, Mimir, Loki, Grafana monitoring stack (docker-compose + systemd)
  license: MIT
  min_ansible_version: "2.16"
dependencies:
  - role: docker
